# Generated by Django 6.1.1 on 2026-09-26 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='tag',
        ),
    ]
